# Generated by Django 4.0.5 on 2023-02-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_becomevendor_options'),
        ('store', '0003_remove_vendor_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='BecomeVendor', to='userprofile.becomevendor'),
        ),
    ]
