# Generated by Django 4.0.5 on 2023-02-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_vendor_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_user',
        ),
    ]
