# Generated by Django 4.0.5 on 2023-02-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_id', models.IntegerField(null=True)),
                ('s_name', models.CharField(max_length=50)),
                ('sp_image', models.ImageField(blank=True, upload_to='media/uploads/service_provider_image/')),
                ('sp_contact', models.TextField(max_length=200)),
                ('sp_star', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='media/uploads/service_image/')),
                ('video', models.FileField(blank=True, upload_to='media/uploads/service_video/')),
                ('price', models.IntegerField()),
                ('stars', models.IntegerField(null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='services.serviceprovider')),
            ],
        ),
    ]
