# Generated by Django 4.0.5 on 2023-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_providermessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermessage',
            name='subject',
            field=models.CharField(default='Querry about service ', max_length=100),
        ),
    ]
