# Generated by Django 4.0.5 on 2023-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_s_name_serviceprovider_sp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='subject',
            field=models.CharField(default='Request to add service ', max_length=100),
        ),
        migrations.AlterField(
            model_name='providermessage',
            name='subject',
            field=models.CharField(default='Querry about service ', max_length=100),
        ),
    ]
