# Generated by Django 4.0.5 on 2023-02-18 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomevendor',
            options={'verbose_name_plural': 'Become Vendors'},
        ),
        migrations.AddField(
            model_name='becomevendor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
