# Generated by Django 4.0.5 on 2023-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_becomevendor_options_becomevendor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
