# Generated by Django 4.0.5 on 2023-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_becomevendor_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomevendor',
            name='vendor_email',
            field=models.EmailField(max_length=100),
        ),
    ]
