# Generated by Django 4.0.5 on 2023-02-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_becomevendor_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomevendor',
            name='vendor_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
