# Generated by Django 4.0.5 on 2023-02-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_customuser_is_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomevendor',
            options={'verbose_name_plural': 'Become a service provider'},
        ),
    ]
