# Generated by Django 4.0.5 on 2023-02-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_customuser_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_vendor',
        ),
    ]
