# Generated by Django 4.0.5 on 2023-02-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_becomevendor_user_customuser_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomevendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
