# Generated by Django 4.0.5 on 2023-02-18 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_alter_becomevendor_options_alter_becomevendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomevendor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
