# Generated by Django 4.0.5 on 2023-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_alter_becomevendor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomevendor',
            options={},
        ),
        migrations.RemoveField(
            model_name='becomevendor',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
